-- MySQL Script generated by MySQL Workbench
-- Thu May 22 15:45:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadastroprodutos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cadastroprodutos` ;

-- -----------------------------------------------------
-- Schema cadastroprodutos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadastroprodutos` DEFAULT CHARACTER SET utf8 ;
USE `cadastroprodutos` ;

-- -----------------------------------------------------
-- Table `cadastroprodutos`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastroprodutos`.`usuario` ;

CREATE TABLE IF NOT EXISTS `cadastroprodutos`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `setor` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastroprodutos`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastroprodutos`.`produto` ;

CREATE TABLE IF NOT EXISTS `cadastroprodutos`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadastroprodutos`.`saida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadastroprodutos`.`saida` ;

CREATE TABLE IF NOT EXISTS `cadastroprodutos`.`saida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(100) NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_produto_saida_idx` (`id_produto` ASC),
  INDEX `id_usuario_saida_idx` (`id_usuario` ASC),
  CONSTRAINT `id_produto_saida`
    FOREIGN KEY (`id_produto`)
    REFERENCES `cadastroprodutos`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario_saida`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cadastroprodutos`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

